---
galaxy_info:
  role_name: rhel_image
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: rhel_image role
  license: GPLv3+
  min_ansible_version: "2.13"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - imagebuilder
    - build
    - image
    - rhel
    - edge
dependencies: []
